using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace K_amazon.Models
{
    public class Brand
    {
        [Key] // is used to inform the framework that this is a Primary Key field
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // is used to specify that the field’s values will be generated by the database.
        public int Id { get; set; }
        [StringLength(50)] // specifies the maximum size for string fields.
        [Required] // to ensure that data is mandatory when inserting or updating data for this field
        public string Name { get; set; }
    }
}
